# Generated by Django 5.2.8 on 2025-12-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_finalsubmission_alter_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.submission'),
        ),
    ]
