# Generated by Django 5.2.8 on 2025-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_finalsubmission_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
