# Generated by Django 5.2.8 on 2025-12-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submission_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
