# Generated by Django 5.2.8 on 2025-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_task_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('text', 'Text'), ('python', 'Python')], default='text', max_length=16),
        ),
    ]
