# Generated by Django 5.2.8 on 2026-02-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_task_duration_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_at',
        ),
    ]
